frameworkVersion: '2'

service: isTrust

provider:
    name: aws
    runtime: nodejs12.x
    stage: production
    region: eu-west-3
    lambdaHashingVersion: '20201221'

functions:
    hello:
        handler: hello.handler
        events:
            - httpApi:
                  path: /
                  method: get
        timeout: 5

package:
    artifact: 'pack/isTrust-API.zip'

plugins:
  - serverless-offline
